CREATE TABLE TICKET(
  TICKET_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  SHOW_ID VARCHAR(50) NOT NULL,
  SEAT INTEGER NOT NULL,
  IS_VIP BOOLEAN,
  IS_FREE BOOLEAN,
  PRICE INTEGER );

CREATE TABLE AUDITORIUM(
  AUDITORIUM_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME VARCHAR(50) NOT NULL,
  SEATS INTEGER NOT NULL,
  VIP_SEATS VARCHAR(50) );

CREATE TABLE CLIENT(
  CLIENT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CLIENTNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL);

CREATE TABLE CLIENT_TICKETS(
  CLIENT_ID INTEGER NOT NULL,
  TICKET_ID INTEGER NOT NULL );

CREATE TABLE EVENT(
  EVENT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME VARCHAR(50) NOT NULL,
  PRICE INTEGER NOT NULL,
  EVENT_RATE VARCHAR(10) NOT NULL );

CREATE TABLE SHOW(
  SHOW_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EVENT_ID INTEGER NOT NULL,
  SHOW_DATE DATE NOT NULL,
  AUDITORIUM_ID INTEGER NOT NULL );

CREATE TABLE EVENT_COUNTERS(
  EVENT_ID INTEGER NOT NULL,
  TICKET_PRICE INTEGER,
  BY_NAME INTEGER,
  BOOKED_TICKETS INTEGER );

CREATE TABLE DISCOUNT_COUNTERS(
  CLIENT_ID INTEGER NOT NULL,
  COUNT INTEGER );

CREATE TABLE TOTAL_DISCOUNTS(
  DISCOUNT_COUNT INTEGER );

